### ISSUE TITLE
more detail requested for ubuntu

### ISSUE THREAD

**Issue by jamenlang** [tarickb/sasl-xoauth2#2]
During testing on Debian I decided to try ubuntu 18.04.3 LTS to see if the PPA would work better for me.

It installed just fine, but I don't know how to get postfix to use / show that it's using the sasl2 shared library.

from the vanilla installation of 18.04.3 LTS, I ran the following commands:

```
apt-get update
ldd /usr/sbin/postfix <- noticed sasl is not listed.
```

followed the documentation mostly from here for chrooting postfix:
https://www.palawandigital.com/configuring-postfix-encryption-ubuntu/

I still don't see it with ldd /usr/sbin/postfix although saslauthd is loaded active and running as a service.

When a test message is sent out I get a message in syslog saying authentication required, no mention of xoauth2 with verbose logging enabled.

Do you have some sort of configuration guide to set this up from scratch with example configs handy?

**Comment by tarickb** [comment]
I wouldn't expect `ldd` to show you a dependency on libsasl-xoauth2.so because SASL won't try to load that library until it's told to. Did you set up Postfix as described in the [README](https://github.com/tarickb/sasl-xoauth2/blob/master/README.md)? That should be everything necessary to get Postfix to use SASL (and to get SASL to use XOAUTH2), but it's been a while since I wrote that up. I'll try with a fresh Ubuntu install to make sure the instructions make sense.

**Comment by tarickb** [comment]
I tried with a fresh install of 18.04.3 and indeed the instructions are sufficient. I updated the README to be more explicit about where to put the OAuth token file and about the need to chown the token directory. Hope that helps!

**Comment by jamenlang** [comment]
I got it working, I was missing commas in the /etc/sasl-xoauth2.conf file and I realized that I was chrooted so the var spool file was the one I actually needed to modify.

Thank you so much for this, with google switching off password apps I think you're going to get a lot of users pretty quickly.

**Comment by tarickb** [comment]
Glad it worked! I suspect you're the first user of this code besides me, so it's good to hear it's not wildly broken. :)
