### ISSUE TITLE
Desired location of libsasl-xoauth2.so

### ISSUE THREAD

**Issue by jamenlang** [tarickb/sasl-xoauth2#6]
Hello, I'm trying to make another relay server using Ubuntu 20.04.1, 

I installed this from the PPA.

I'm getting the No worthy mechs found message, but before that I'm seeing Exception during init: * Line 5, Column 3#012 Missing ',' or '}' in object declaration.

You mentioned in the readme that the libsasl-xoauth2.so might have been placed in the wrong directory, but it looks like it's in the same place as my last test server.

/usr/lib/x86_64-linux-gnu/sasl2/libsasl-xoauth2.so

**Comment by tarickb** [comment]
That error message you're seeing (["Exception during init: ..."](https://github.com/tarickb/sasl-xoauth2/blob/master/src/config.cc#L109)) is where the problem lies, I believe. Can you double-check that your config file (`/etc/sasl-xoauth2.conf`) is valid JSON? From the error it looks like you might be missing a comma somewhere.

**Comment by jamenlang** [comment]
I don't think I changed the /etc/sasl-xoauth2.conf file at all since I opened the issue, but it's working today. Is that the right directory for libsasl-xoauth2.so?

**Comment by tarickb** [comment]
Yeah, it's the right directory. If Postfix hadn't found the library, you wouldn't have seen that "Exception during init" message. Are you no longer seeing that message?

**Comment by jamenlang** [comment]
No the message is still there, but now I only when testing issue #7.
