### ISSUE TITLE
Postfix, xoauth and plain different depending on user.

### ISSUE THREAD

**Issue by YGGrAGcTtp** [tarickb/sasl-xoauth2#73]
Thanks for you great work!

I got this working nicely using Office365, however I have some accounts which need to use xoauth2 while others still need to use plain authentication.

Is there a way in Postfix to using sasl-xoauth2 for single users only, while others keep using PLAIN authentication?

Kind Regerds,

Ek

**Comment by tarickb** [comment]
I'm not sure I entirely understand what you mean by "users" in this context. Are you trying to configure different relay hosts in Postfix, some of which require XOAUTH2 (like Outlook) and some that don't support it? In principle this should "just work" if you set `smtp_sasl_mechanism_filter` correctly (see the [README](https://github.com/tarickb/sasl-xoauth2#configure-mail-agent)) because Postfix will fall back to another auth mechanism if XOAUTH2 isn't supported by the server.

Would you be open to sharing the config files for what you've tried so far (with sensitive parts redacted of course)?

**Comment by YGGrAGcTtp** [comment]
Many thanks for looking into this, much appreciated. I kinda came to the same conclusion unfortunately.
